### ISSUE TITLE
403 error to create blockchain with the academy tutorial

### ISSUE THREAD

**Issue by jsirtaine** [ava-labs/avalanche-starter-kit#23]
I have an issue when I follow the tutorial of the academy.
On codespace, when I try to create my blockchain, I have this issue : Error: failed doing request https://api.github.com/repos/ava-labs/avalanche-cli/releases/latest: unexpected http status code: 403

![image](https://github.com/user-attachments/assets/f72b70e5-a6d3-4cb4-9c39-9b1fa70ffde9)

**Comment by containerman17** [comment]
My guess is that the Avalanche CLI checks for updates, fails to do so, and then fails completely. IMHO, it would be better if it just skipped the update if it fails.

**Comment by ashucoder9** [comment]
Refreshing it a few times and relaunching the codespaces temporarily fixed the issue for me.

Next Steps: as @containerman17 suggested, we'll skip the CLI update in case there is an error in the update request.

**Comment by felipemadero** [comment]
Q: was this the first command executed after creating the codespace? if not, which was the previous interaction?
trying to figure out if a rate limit was hit

**Comment by felipemadero** [comment]
Adding CLI Config for codespace github token: https://github.com/ava-labs/avalanche-starter-kit/pull/24 this should fix the issue for rate limited cases
